### ISSUE TITLE
一些有关open ai速率的问题

### ISSUE THREAD

**Issue by JUSTMonika15** [yxc0915/srt_translator#3]
第一次提issue见谅，不知道要什么形式
就是我在使用 的时候，发现现有的time sleep
（                    # 重试间隔（指数退避）
                    time.sleep(2 ** retry)）
 部分还是很容易有字幕翻译失败，所以我是直接改成了60，没有什么失败的翻译了。用的是gpt 4o模型。
 非常感谢大佬的项目！很简单易懂，帮了我很多！感谢大佬！

**Comment by yxc0915** [comment]
很高兴这个项目能帮到你(●'◡'●)
